name: Build and Push Data-restore docker Image
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build from'
        required: true
        default: 'dev'

jobs:
  build-push-image:
    runs-on: [self-hosted, ci-runner]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build_push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./docker/data-restore/Dockerfile
        tags: |
          matterlabs/data-restore:${{ steps.vars.outputs.sha_short }}
          matterlabs/data-restore:latest
