name: Loadtest
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Deploy Stage]
    types:
      - completed


# Disable simultaneous deployments into a single environment
concurrency: loadtest

env:
  ZKSYNC_ENV: loadtest

jobs:
  setup:
    name: Setup
    uses: matter-labs/zksync-dev/.github/workflows/setup.runtime.yml@dev
    with:
      environment: goerli-beta
      create-deployment: true

  loadtest:
    name: Perform loadtest
    runs-on: [self-hosted, ci-runner]
    container: rust:1.67
    env:
      WEB3_URL: ${{ secrets.CI_LOADTEST_WEB3_URL }}
      MASTER_WALLET_PK: ${{ secrets.CI_LOADTEST_MAIN_PRIVKEY }}
      ACCOUNTS_AMOUNT: 20
      OPERATIONS_PER_ACCOUNT: 20
      MAIN_TOKEN: "wBTC"
      ZKSYNC_RPC_ADDR: "https://goerli-api.zksync.io/jsrpc"
      ETH_NETWORK: "goerli"
      ALLOWED_PERCENT: 10
      RUST_LOG: loadnext=debug
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Run loadtest
        run: cargo run --bin loadnext


  notify:
    runs-on: ubuntu-latest
    needs: [loadtest]
    if: always() && !cancelled()
    steps:
      - uses: technote-space/workflow-conclusion-action@482bb0dbebad067b3b26ca4f6222c4023cf51ccf # v2
      -
        name: Notify to Mattermost (on incidents)
        uses: tferreira/matterfy@releases/v1
        if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
        with:
          type: failure
          job_name: '*Loadtest failed*'
          icon_emoji: octocat
          channel: 'ci-notifications'
          url: ${{ secrets.MATTERMOST_WEBHOOK }}
