name: publish zk-environment docker image

on:
  pull_request:
    branches:
      - dev
    types: [closed]
    paths:
      - "docker/zk-environment/Dockerfile"
      - ".github/workflows/zk-environment.publish.yml"
  workflow_dispatch:
    branches:
      - "dev"

jobs:
  push_to_registry:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, ci-runner]
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # v2.7.0
        with:
          push: true
          tags: "matterlabs/zk-environment:latest"
          file: docker/zk-environment/Dockerfile
          no-cache: true
